"""The reviewable product list that sits between the tools.

`restock scan` writes it, you edit it, `restock fill` reads it. That file is
the whole point of the design: it is where a human decides what gets bought.

An entry is one of two shapes:

    - id: "304368923"                 # a specific product
      name: "Tesco Chicken 400G"
      qty: 1
      always: true

    - name: "Salmon fillets"          # a choice between equivalent products
      qty: 1
      always: true
      oneof:
        - id: "296920881"
          name: "Tesco 2 Boneless Salmon Fillets 260G"
        - id: "309747513"
          name: "Tesco Boneless Salmon Fillets 4 Pack 520g"

`always: true` means "buy this every week". Entries without it are the rest of
your repertoire: `fill` leaves them alone unless something asks for them.

`oneof` means "these are the same thing in different sizes — buy whichever is
best value this week". `scan` never generates these, deliberately: telling a
genuine either/or (a 2-pack vs a 4-pack) from a progression (sizes moved
through once, 1 -> 2 -> 3) needs a human. Use `restock variants` to see the
candidates.

We emit the YAML by hand rather than via `yaml.dump` so comments and ordering
survive. Reading goes through `yaml.safe_load`, so any valid YAML you write by
hand is accepted.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import yaml

from .orders import Regular

HEADER = """\
# Tesco regulars — the shopping list `restock fill` works from.
#
# Generated by `restock scan` on {date}, from your last {n_orders} Tesco orders.
# Ordered most-frequently-bought first. The comment above each product is the
# evidence for it: "7/{n_orders}" means it appeared in 7 of those orders.
#
#   always: true   buy this every week. `fill` adds only these by default.
#   qty            how many to buy. `fill` sets this figure, it never adds to it.
#   skip: true     keep the entry on the list but don't buy it.
#
# Entries without `always` are the rest of your repertoire — `fill --all` adds
# them, and in future they're what an incoming shopping list gets matched to.
#
# To make an entry a choice between sizes, replace its `id` with an `oneof`
# list and `fill` will pick whichever is best value that week:
#
#   - name: "Salmon fillets"
#     qty: 1
#     always: true
#     oneof:
#       - id: "296920881"
#         name: "Tesco 2 Boneless Salmon Fillets 260G"
#       - id: "309747513"
#         name: "Tesco Boneless Salmon Fillets 4 Pack 520g"
#
# Run `restock variants` to see which of your products look like such choices.
# It does not guess for you: sizes you move through once (1 -> 2 -> 3) look
# identical to a genuine either/or in the data, and buying the cheapest of
# those would be wrong.
#
# `id` is Tesco's product id and is what actually gets added to the basket.
# `name` is a human label only, so renaming it is safe; changing `id` is not.
# Re-running `scan` overwrites this file — use --output to write elsewhere.

products:
"""


@dataclass(frozen=True)
class Option:
    """One concrete product that could satisfy an entry."""

    product_id: str
    name: str


@dataclass(frozen=True)
class Entry:
    """One line of the regulars file, as `fill` sees it."""

    label: str
    options: tuple[Option, ...]
    quantity: int = 1
    always: bool = False

    @property
    def is_choice(self) -> bool:
        """True if `fill` has to pick between equivalent products."""
        return len(self.options) > 1

    @property
    def product_id(self) -> str:
        """The only product id, for entries that aren't a choice."""
        if self.is_choice:
            raise ValueError(f"{self.label!r} is a choice of {len(self.options)}")
        return self.options[0].product_id


def render(regulars: list[Regular], *, date: str, n_orders: int, always_at: float) -> str:
    """Render the regulars list as a commented, hand-editable YAML document."""
    return HEADER.format(date=date, n_orders=n_orders) + "".join(
        _entry_lines(r, always_at) for r in regulars
    )


def write(
    path: Path,
    regulars: list[Regular],
    *,
    date: str,
    n_orders: int,
    always_at: float,
) -> None:
    path.write_text(
        render(regulars, date=date, n_orders=n_orders, always_at=always_at),
        encoding="utf-8",
    )


def load(path: Path, *, always_only: bool = False) -> list[Entry]:
    """Read a regulars file.

    Entries marked `skip: true` are dropped. With `always_only`, entries not
    marked `always: true` are dropped too.

    Raises ValueError with a pointed message on malformed input — this file is
    hand-edited, so a typo here is expected and deserves a real explanation
    rather than a KeyError from somewhere deep in the basket code.
    """
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or "products" not in raw:
        raise ValueError(f"{path}: expected a top-level 'products:' list.")
    products = raw["products"]
    if not isinstance(products, list):
        raise ValueError(f"{path}: 'products' must be a list.")

    entries: list[Entry] = []
    # Where each product id was seen, so a duplicate can name both entries.
    seen: dict[str, str] = {}
    for n, item in enumerate(products, start=1):
        if not isinstance(item, dict):
            raise ValueError(f"{path}: product #{n} is not a mapping.")
        if item.get("skip"):
            continue
        entry = _entry(path, n, item)
        # Catching this matters: folding sizes into a `oneof` while leaving the
        # old standalone entries in place is an easy edit to make, and it would
        # quietly buy the same thing twice.
        for option in entry.options:
            if option.product_id in seen:
                raise ValueError(
                    f"{path}: product id {option.product_id} appears in two "
                    f"entries — {seen[option.product_id]!r} and {entry.label!r}. "
                    "Remove one, or `fill` would buy it twice."
                )
            seen[option.product_id] = entry.label
        if always_only and not entry.always:
            continue
        entries.append(entry)
    return entries


def _entry(path: Path, n: int, item: dict) -> Entry:
    """Build one Entry from a raw mapping, validating as we go."""
    quantity = item.get("qty", 1)
    if not isinstance(quantity, int) or isinstance(quantity, bool) or quantity < 1:
        raise ValueError(
            f"{path}: product #{n} has qty={quantity!r}; "
            "it must be a whole number of 1 or more."
        )

    if "oneof" in item:
        if "id" in item:
            raise ValueError(
                f"{path}: product #{n} has both 'id' and 'oneof'; use one or the other."
            )
        raw_options = item["oneof"]
        if not isinstance(raw_options, list) or not raw_options:
            raise ValueError(f"{path}: product #{n} has an empty 'oneof' list.")
        options = []
        for choice in raw_options:
            if not isinstance(choice, dict) or "id" not in choice:
                raise ValueError(
                    f"{path}: product #{n} has a 'oneof' entry with no 'id'."
                )
            options.append(
                Option(str(choice["id"]), str(choice.get("name", choice["id"])))
            )
        label = str(item.get("name", options[0].name))
        return Entry(label, tuple(options), quantity, bool(item.get("always")))

    if "id" not in item:
        raise ValueError(f"{path}: product #{n} has no 'id' (or 'oneof').")
    product_id = str(item["id"])
    label = str(item.get("name", product_id))
    return Entry(
        label, (Option(product_id, label),), quantity, bool(item.get("always"))
    )


APPENDED_HEADER = """
# --- Added by `restock update` on {date}, from your last {n_orders} orders ---
# Newly frequent products that weren't already on the list. Everything above
# is untouched. Review these: set `always: true` on the staples, fold sizes of
# one product into a `oneof`, delete what you don't want.
"""


def all_product_ids(path: Path) -> set[str]:
    """Every product id the file mentions, whatever shape the entry is.

    Deliberately includes `skip: true` entries and every `oneof` option:
    `update` uses this to decide what is "new", and a product you have
    explicitly skipped must not come back every week.
    """
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or not isinstance(raw.get("products"), list):
        raise ValueError(f"{path}: expected a top-level 'products:' list.")

    ids: set[str] = set()
    for item in raw["products"]:
        if not isinstance(item, dict):
            continue
        if "id" in item:
            ids.add(str(item["id"]))
        for choice in item.get("oneof") or []:
            if isinstance(choice, dict) and "id" in choice:
                ids.add(str(choice["id"]))
    return ids


def append(
    path: Path, new: list[Regular], *, date: str, n_orders: int, always_at: float
) -> None:
    """Append new products to an existing regulars file.

    Appends rather than rewrites, on purpose. The file carries hand edits,
    comments, `always` flags and `oneof` groups that no round-trip through a
    YAML serialiser would survive intact, so everything already there is left
    byte-for-byte alone.
    """
    if not new:
        return
    existing = path.read_text(encoding="utf-8")
    # A list item can only continue the sequence from the start of a line.
    separator = "" if existing.endswith("\n") else "\n"
    body = APPENDED_HEADER.format(date=date, n_orders=n_orders) + "".join(
        _entry_lines(r, always_at) for r in new
    )
    path.write_text(existing + separator + body, encoding="utf-8")


def _entry_lines(r: Regular, always_at: float) -> str:
    """Render one product entry, as both `render` and `append` need it."""
    lines = [
        f"  # {r.order_count}/{r.total_orders} orders\n",
        f'  - id: "{r.product_id}"\n',
        f"    name: {json.dumps(r.name)}\n",
        f"    qty: {r.quantity}\n",
    ]
    if r.frequency >= always_at:
        lines.append("    always: true\n")
    return "".join(lines)
